### ISSUE TITLE
Not an issue - but a question

### ISSUE THREAD

**Issue by Lemon-Soup** [fzao/caRamel#1]
Hello! This package is fantastic. 
For my use case, I am wondering whether it is possible to use more complex constraints on the objective functions than just upper and lower bounds for the parameters? For example, "the overall amount of a certain subset of the parameters used must be lower than a certain level". I would happy to discuss this in some other way (e.g. via email) if more convenient. Thank you :)

**Comment by fzao** [comment]
Hello, thanks for your feedback. Yes it is possible to deal with particular constraints. I wrote a vignette doc in the package on this topic. Hope this helps. Fabrice

**Comment by Lemon-Soup** [comment]
Thank you! :)
