### ISSUE TITLE
would be good to protect against NA values in dominate()

### ISSUE THREAD

**Issue by hstov3** [fzao/caRamel#2]
This package has been very helpful to us for visualizing many-objective optimization results.  Thank you!

With 100s of thousands of potential solutions, the dominate() method runs for upwards of an hour (as expected).

We had a corrupted input file where the last line was truncated and there was one row with an NA value.  In this case, dominate() continued to run with the busy CPU utilization as if it was still calculating values, but it was forever hung.  It took awhile to figure out it wasn't working correctly, and then a bit of debugging to figure out why.  

Although, this is clearly an error in the input data, it would be good to protect against this case.  To me, a better solution would be to detect any NAs in the input and fail immediately with a corresponding message.  

The following demonstrates: 

This runs fine as per the documentation: 

    mat_ok <- matrix(runif(20),10,2)
    mat_ok              # view the matrix
    any(is.na(mat_ok))  # no NAs
    caRamel::dominate(mat_ok) # completes

This hangs forever with high CPU:

    mat_w_na <- mat_ok
    mat_w_na[10,1] <-NA   # same matrix as above with one NA value
    mat_w_na              # view the new matrix
    any(is.na(mat_w_na))  # at least one NA
    caRamel::dominate(mat_w_na)  # hangs in busy state

**Comment by fzao** [comment]
Thanks for your feedback.

I will probably follow your suggestion in order to solve the problem

**Comment by fzao** [comment]
Solved issue (commit 675ba27c1ddfe42bb6b5b51c3338dc511cad08e7)
