### ISSUE TITLE
Suggestion: Passing extra arguments to func in the caRamel function

### ISSUE THREAD

**Issue by ghost** [fzao/caRamel#3]
Hello, it would be great to be able to pass an arbitrary number of parameters to "func" in the caRamel function if we have variables coming from the overall script that are used in the objective functions. E.g.:

```
my_obj_func <- function(i, var1, var2, var3) {
  ...
  return(goodness_of_fit)
}
```

```
caRamel(
  ...
  func=my_obj_func,
  ...
  carallel=TRUE, numcores=10,
  var1=aaa, var2=bbb, var3=ccc
)
```

If the objective function is quite long with many variables as in my case, it would avoid hard coding every variable value inside the objective function, especially if the function is reused many times in the script...

**Comment by fzao** [comment]
Thanks for this comment. 

Is the "..." argument the solution for you (passing "..." from caRamel() to func())?

**Comment by ghost** [comment]
Yes exactly I was thinking about that. I think it's a standard thing in R but I'm not sure how it is fully implemented beyond the ... in the function definition... Great package by the way.

**Comment by fzao** [comment]
Adding an additional parameter ('worklist') to caRamel in order to have extra values available in the user's function

See commit #5a48e3fb716ceeef721b3a44bdca09eeaf3aad26
