### ISSUE TITLE
How to pass parameters in caRamel for discontinuous variables

### ISSUE THREAD

**Issue by Messi0617** [fzao/caRamel#4]
I want to add an output variable for subcatch, which has only a few options, such as choices<- list ("x4"=c (207, 39, 206, 214, 121)). Can I set the range of this variable in caRamel? How to set it up？ I look forward to your reply and help very much, and I would greatly appreciate any of your suggestions.

**Comment by fzao** [comment]
Hello,
Sorry for the late answer. caRamel does not deal explicitly with the discrete variables. You can try to implement a dead-or-alive approach with your objective functions or add inequality constraints for instance but I don't think it will be relevant.
